name: Flutter_Project
description: "Typing Game"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.0.0
  google_fonts: 6.1.0


  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
